version: "3.7"

services:
  jekyll:
    image: jekyll/jekyll:3.7
    command: jekyll serve --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: production
